FROM alpine:3.17
RUN apk add --no-cache ca-certificates


ADD tile38-server.alp /usr/local/bin/tile38-server
ADD tile38-cli.alp /usr/local/bin/tile38-cli

RUN addgroup -S tile38 && \
    adduser -S -G tile38 tile38 && \
    mkdir /data && chown tile38:tile38 /data

VOLUME /data

EXPOSE 9851 9821
CMD ["tile38-server", "-d", "/data","--metrics-addr=0.0.0.0:9821"]
