name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: Package
        run: make package

      - name: Docker push
        env:
          DOCKER_LOGIN: tidwall
          DOCKER_USER: tile38
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./scripts/docker-push.sh
